### ISSUE TITLE
size matters

### ISSUE THREAD

**Issue by tissatussa** [kz04px/4ku#157]
Congrats with the new v2.0! The Changelog is impressive .. you guys certainly know how to build a chess engine, using all known techniques optimally, to even get all code into 4 Kb !! Regarding that size : why is the released (linux) asset 2.9 Mb ? Is it because that version will optimally run on ALL linux distros ? My compiled version is only 59.7 Kb !

**Comment by GediminasMasaitis** [comment]
Thank you!

Yes, the full-sized executables for release are statically linked, (built using the `--static` flag).
In theory this includes the standard library components used in the executable, making it independent on the stdlib version in the system, in theory making it portable to any distro (though this was never properly tested).
Similarly, on Windows it makes the executable not dependent on a having mingw installed.

Of course, this then bloats the size because over 99% of the code is not 4ku code but standard library code :)
